name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LC_ALL: en_US.UTF-8

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ \
          cmake \
          make \
          pkg-config \
          libcurl4-openssl-dev \
          libpqxx-dev \
          postgresql \
          locales

    - name: Install Qt6
      run: |
        sudo apt-get install -y \
          qt6-base-dev \
          qt6-base-dev-tools \
          libqt6core6 \
          libqt6gui6 \
          libqt6widgets6

    - name: Generate locale
      run: |
        sudo locale-gen en_US.UTF-8

    - name: Configure Postgresql
      run: |
        sudo pg_ctlcluster 14 main start
        echo "lc_messages = 'en_US.UTF-8'" | sudo tee -a /etc/postgresql/14/main/postgresql.conf
        echo "host all all 0.0.0.0/0 trust" | sudo tee -a /etc/postgresql/14/main/pg_hba.conf
        echo "listen_addresses = '*'" | sudo tee -a /etc/postgresql/14/main/postgresql.conf
        sudo systemctl restart postgresql

    - name: Create and configure database
      run: |
        sudo -u postgres psql -c "CREATE DATABASE mydb WITH ENCODING 'UTF8' LC_COLLATE 'en_US.UTF-8' LC_CTYPE 'en_US.UTF-8' TEMPLATE template0;"
        sudo -u postgres psql -c "CREATE USER service WITH PASSWORD '11111111';"
        sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE mydb TO service;"

    - name: Prepare QCustomPlot
      run: |
        cp -v ./lib/qcustomplot/qcustomplot.h ./QT/
        cp -v ./lib/qcustomplot/qcustomplot.cpp ./QT/

    - name: Build
      run: |
        rm -rf build
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j$(nproc)

    - name: Upload application artifact
      uses: actions/upload-artifact@v4
      with:
        name: ExchangeRateCbr-app
        path: build/ExchangeRateCbr
        if-no-files-found: error
