name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PG_LOCALE: en_US.UTF-8  # Set UTF-8 locale for PostgreSQL
      LC_ALL: C.UTF-8         # Set UTF-8 locale for application

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ libcurl4-openssl-dev libpqxx-dev pkg-config postgresql locales 
        sudo locale-gen en_US.UTF-8  # Generate UTF-8 locale

    - name: Configure PostgreSQL
      run: |
        # Configure UTF-8 encoding
        echo "lc_messages = 'en_US.UTF-8'" | sudo tee -a /etc/postgresql/*/main/postgresql.conf
        echo "lc_monetary = 'en_US.UTF-8'" | sudo tee -a /etc/postgresql/*/main/postgresql.conf
        echo "lc_numeric = 'en_US.UTF-8'" | sudo tee -a /etc/postgresql/*/main/postgresql.conf
        echo "lc_time = 'en_US.UTF-8'" | sudo tee -a /etc/postgresql/*/main/postgresql.conf
        
        # Allow all connections
        echo "host all all 0.0.0.0/0 trust" | sudo tee -a /etc/postgresql/*/main/pg_hba.conf
        echo "listen_addresses = '*'" | sudo tee -a /etc/postgresql/*/main/postgresql.conf
        
        sudo systemctl restart postgresql

    - name: Create and configure database
      run: |
        sudo -u postgres psql -c "CREATE DATABASE mydb WITH ENCODING 'UTF8' TEMPLATE template0;"
        sudo -u postgres psql -c "CREATE USER service WITH PASSWORD '11111111';"
        sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE mydb TO service;"
        sudo -u postgres psql -d mydb -c "GRANT ALL ON SCHEMA public TO service;"
        sudo -u postgres psql -d mydb -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO service;"

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make

    # Сохраняем артефакт сборки
    - name: Upload application artifact
      uses: actions/upload-artifact@v4
      with:
        name: ExchangeRateCbr-app
        path: build/ExchangeRateCbr
        if-no-files-found: error

    - name: Run executable
      run: |
        cd build
        ./ExchangeRateCbr

    - name: Inspect database content
      if: always()  # Run even if previous step fails
      run: |
        echo "Database structure:"
        sudo -u postgres psql -d mydb -c "\d"
        
        echo "Table structure (exdc):"
        sudo -u postgres psql -d mydb -c "\d exdc"
        
        echo "Data in exdc table:"
        sudo -u postgres psql -d mydb -c "SELECT * FROM exdc;"
